// Seed data for the standalone demo — mirrors the FastAPI backend seed.

window.FRAMEWORKS_SEED = [
  {
    code: "ISO42001",
    name: "ISO/IEC 42001:2023 — AI Management System",
    version: "2023",
    description:
      "International standard for establishing, implementing, maintaining and continually improving an AI Management System (AIMS).",
    controls: [
      ["4.1", "Understanding the organization and its context", "Context", "Determine external and internal issues relevant to the AIMS."],
      ["4.2", "Understanding needs and expectations of interested parties", "Context", "Identify stakeholders and their requirements concerning AI systems."],
      ["4.3", "Determining the scope of the AI management system", "Context", "Define boundaries and applicability of the AIMS."],
      ["4.4", "AI management system", "Context", "Establish, implement, maintain and continually improve the AIMS."],
      ["5.1", "Leadership and commitment", "Leadership", "Top management accountability for the AIMS."],
      ["5.2", "AI policy", "Leadership", "Establish and communicate an AI policy aligned to strategy."],
      ["5.3", "Roles, responsibilities and authorities", "Leadership", "Assign AI-related roles, responsibilities and authorities."],
      ["6.1", "Actions to address risks and opportunities", "Planning", "Plan actions to address AI risks and opportunities."],
      ["6.1.2", "AI risk assessment", "Planning", "Define and apply an AI risk assessment process."],
      ["6.1.3", "AI risk treatment", "Planning", "Define and apply an AI risk treatment process including SoA."],
      ["6.1.4", "AI system impact assessment", "Planning", "Conduct impact assessments for AI systems on individuals, groups and society."],
      ["6.2", "AI objectives and planning to achieve them", "Planning", "Establish measurable AI objectives consistent with policy."],
      ["6.3", "Planning of changes", "Planning", "Plan and control changes to the AIMS."],
      ["7.1", "Resources", "Support", "Determine and provide the resources needed for the AIMS."],
      ["7.2", "Competence", "Support", "Ensure competence of persons affecting AI performance."],
      ["7.3", "Awareness", "Support", "Ensure persons are aware of the AI policy and their contribution."],
      ["7.4", "Communication", "Support", "Determine internal and external communications relevant to AIMS."],
      ["7.5", "Documented information", "Support", "Maintain and control documented information required by the AIMS."],
      ["8.1", "Operational planning and control", "Operation", "Plan, implement and control processes to meet requirements."],
      ["8.2", "AI risk assessment (operational)", "Operation", "Perform operational AI risk assessments at planned intervals."],
      ["8.3", "AI risk treatment (operational)", "Operation", "Implement AI risk treatment plans."],
      ["8.4", "AI system impact assessment (operational)", "Operation", "Carry out AI system impact assessments at planned intervals."],
      ["9.1", "Monitoring, measurement, analysis and evaluation", "Performance", "Determine what to monitor and measure."],
      ["9.2", "Internal audit", "Performance", "Conduct internal audits at planned intervals."],
      ["9.3", "Management review", "Performance", "Top management to review the AIMS at planned intervals."],
      ["10.1", "Continual improvement", "Improvement", "Continually improve the suitability, adequacy and effectiveness of the AIMS."],
      ["10.2", "Nonconformity and corrective action", "Improvement", "React to nonconformities and take corrective action."],
      ["A.2.2", "AI policy", "Annex A - Policies", "Document and approve AI-specific policies."],
      ["A.2.3", "Alignment with other organizational policies", "Annex A - Policies", "Ensure AI policies align with other organizational policies."],
      ["A.3.2", "AI roles and responsibilities", "Annex A - Internal org", "Define AI-related roles and responsibilities."],
      ["A.3.3", "Reporting of concerns", "Annex A - Internal org", "Provide mechanism for reporting AI concerns."],
      ["A.4.2", "Resource documentation", "Annex A - Resources", "Document AI resources (data, tooling, compute, human)."],
      ["A.4.3", "Data resources", "Annex A - Resources", "Document data resources used for AI systems."],
      ["A.4.4", "Tooling resources", "Annex A - Resources", "Document tooling used for AI systems."],
      ["A.4.5", "System and computing resources", "Annex A - Resources", "Document system and compute used for AI systems."],
      ["A.4.6", "Human resources", "Annex A - Resources", "Document required human resources for AI systems."],
      ["A.5.2", "AI system impact assessment process", "Annex A - Impact", "Define a process for AI system impact assessments."],
      ["A.5.3", "Documentation of AI system impact", "Annex A - Impact", "Document AI system impact assessments."],
      ["A.5.4", "Assessing impact on individuals", "Annex A - Impact", "Assess potential consequences for individuals."],
      ["A.5.5", "Assessing societal impact", "Annex A - Impact", "Assess potential consequences for groups and society."],
      ["A.6.1.2", "Objectives for responsible AI development", "Annex A - Lifecycle", "Define objectives for responsible AI development."],
      ["A.6.1.3", "Processes for responsible AI development", "Annex A - Lifecycle", "Establish processes for responsible AI development."],
      ["A.6.2.2", "AI system requirements and specification", "Annex A - Lifecycle", "Specify AI system requirements."],
      ["A.6.2.3", "AI system design and development", "Annex A - Lifecycle", "Document AI system design and development."],
      ["A.6.2.4", "Verification and validation", "Annex A - Lifecycle", "Perform verification and validation."],
      ["A.6.2.5", "Deployment", "Annex A - Lifecycle", "Plan and document deployment."],
      ["A.6.2.6", "Operation and monitoring", "Annex A - Lifecycle", "Operate and monitor AI systems."],
      ["A.6.2.7", "Technical documentation", "Annex A - Lifecycle", "Maintain technical documentation for AI systems."],
      ["A.6.2.8", "AI system recording of event logs", "Annex A - Lifecycle", "Determine logging requirements."],
      ["A.7.2", "Data for development and enhancement of AI", "Annex A - Data", "Define processes for acquiring data."],
      ["A.7.3", "Acquisition of data", "Annex A - Data", "Document data acquisition."],
      ["A.7.4", "Quality of data for AI systems", "Annex A - Data", "Define and ensure data quality."],
      ["A.7.5", "Data provenance", "Annex A - Data", "Record data provenance."],
      ["A.7.6", "Data preparation", "Annex A - Data", "Define data preparation methods."],
      ["A.8.2", "System documentation and information for users", "Annex A - Information", "Provide information for users of AI systems."],
      ["A.8.3", "External reporting", "Annex A - Information", "Enable external stakeholders to report issues."],
      ["A.8.4", "Communication of incidents", "Annex A - Information", "Define plans for communicating incidents."],
      ["A.8.5", "Information for interested parties", "Annex A - Information", "Provide information to interested parties."],
      ["A.9.2", "Processes for responsible use of AI", "Annex A - Use", "Define processes for responsible use of AI."],
      ["A.9.3", "Objectives for responsible use of AI", "Annex A - Use", "Define objectives for responsible AI use."],
      ["A.9.4", "Intended use of the AI system", "Annex A - Use", "Define intended use."],
      ["A.10.2", "Allocating responsibilities", "Annex A - Third parties", "Allocate responsibilities among stakeholders."],
      ["A.10.3", "Suppliers", "Annex A - Third parties", "Ensure suppliers align with responsible AI objectives."],
      ["A.10.4", "Customers", "Annex A - Third parties", "Communicate with customers about AI responsibilities."],
    ],
  },
  {
    code: "EU_AI_ACT",
    name: "EU AI Act (Regulation 2024/1689)",
    version: "2024",
    description:
      "EU regulatory framework for trustworthy AI, including prohibited practices, high-risk system requirements, transparency, and GPAI obligations.",
    controls: [
      ["Art.5", "Prohibited AI practices", "Prohibitions", "Do not deploy prohibited AI practices."],
      ["Art.6", "Classification rules for high-risk AI systems", "High-Risk Classification", "Determine whether the AI system is high-risk per Annex I/III."],
      ["Art.9", "Risk management system", "High-Risk Requirements", "Establish, implement, document and maintain a risk management system."],
      ["Art.10", "Data and data governance", "High-Risk Requirements", "Training, validation and testing data must meet quality criteria."],
      ["Art.11", "Technical documentation", "High-Risk Requirements", "Draw up technical documentation before placing the system on the market."],
      ["Art.12", "Record-keeping", "High-Risk Requirements", "Automatically record events (logs) over the lifetime of the system."],
      ["Art.13", "Transparency and provision of information to deployers", "High-Risk Requirements", "Design systems to be sufficiently transparent for deployers."],
      ["Art.14", "Human oversight", "High-Risk Requirements", "Design systems that can be effectively overseen by natural persons."],
      ["Art.15", "Accuracy, robustness and cybersecurity", "High-Risk Requirements", "Achieve appropriate accuracy, robustness and cybersecurity."],
      ["Art.16", "Obligations of providers", "Provider Obligations", "Comply with obligations of providers for high-risk systems."],
      ["Art.17", "Quality management system", "Provider Obligations", "Put a quality management system in place."],
      ["Art.18", "Documentation keeping", "Provider Obligations", "Keep documentation at the disposal of authorities."],
      ["Art.19", "Automatically generated logs", "Provider Obligations", "Keep logs automatically generated by high-risk systems."],
      ["Art.20", "Corrective actions and duty of information", "Provider Obligations", "Take corrective actions and inform authorities."],
      ["Art.26", "Obligations of deployers", "Deployer Obligations", "Use high-risk systems in accordance with the instructions for use."],
      ["Art.27", "Fundamental rights impact assessment", "Deployer Obligations", "Deployers conduct a fundamental rights impact assessment where required."],
      ["Art.43", "Conformity assessment", "Conformity", "Undergo the relevant conformity assessment procedure."],
      ["Art.47", "EU declaration of conformity", "Conformity", "Draw up a written EU declaration of conformity."],
      ["Art.48", "CE marking", "Conformity", "Affix the CE marking to high-risk AI systems."],
      ["Art.49", "Registration", "Conformity", "Register high-risk AI systems in the EU database."],
      ["Art.50", "Transparency obligations for certain AI systems", "Transparency", "Inform natural persons of interaction with AI; label deep fakes; disclose AI-generated content."],
      ["Art.51", "Classification of GPAI models", "GPAI", "Classify GPAI models and identify systemic risk models."],
      ["Art.53", "Obligations for providers of GPAI models", "GPAI", "Technical documentation, copyright policy, summary of training data."],
      ["Art.55", "Obligations for providers of GPAI models with systemic risk", "GPAI", "Model evaluations, adversarial testing, systemic risk mitigation."],
      ["Art.72", "Post-market monitoring", "Post-Market", "Establish a post-market monitoring system."],
      ["Art.73", "Reporting of serious incidents", "Post-Market", "Report serious incidents to market surveillance authorities."],
      ["Art.95", "Codes of conduct", "Voluntary", "Encourage codes of conduct for non-high-risk AI systems."],
    ],
  },
  {
    code: "NIST_AI_RMF",
    name: "NIST AI Risk Management Framework (AI RMF 1.0)",
    version: "1.0",
    description:
      "Voluntary framework (Govern, Map, Measure, Manage) to help organizations address risks in design, development, use, and evaluation of AI systems.",
    controls: [
      ["GOVERN 1.1", "Legal and regulatory requirements", "Govern", "Legal and regulatory requirements are understood, managed, and documented."],
      ["GOVERN 1.2", "Trustworthy AI characteristics", "Govern", "Trustworthy AI characteristics are integrated into organizational policies."],
      ["GOVERN 1.3", "Risk management processes", "Govern", "Processes determine the level of risk management activities based on risk tolerance."],
      ["GOVERN 1.4", "Risk management documentation", "Govern", "Risk management processes are documented transparently."],
      ["GOVERN 1.5", "Ongoing monitoring and review", "Govern", "Ongoing monitoring and review of the risk management process."],
      ["GOVERN 1.6", "Inventory of AI systems", "Govern", "Mechanisms are in place to inventory AI systems."],
      ["GOVERN 1.7", "Decommissioning processes", "Govern", "Processes for decommissioning AI systems safely."],
      ["GOVERN 2.1", "Roles, responsibilities and lines of communication", "Govern", "Roles and responsibilities are documented."],
      ["GOVERN 2.2", "Training for AI risk management", "Govern", "Personnel have training and are informed of their responsibilities."],
      ["GOVERN 2.3", "Executive leadership", "Govern", "Executive leadership takes responsibility for AI system risk."],
      ["GOVERN 3.1", "Diversity, equity, inclusion and accessibility", "Govern", "AI risk decisions include diverse perspectives."],
      ["GOVERN 3.2", "Workforce risks", "Govern", "Workforce and human-AI configurations are considered."],
      ["GOVERN 4.1", "Organizational culture", "Govern", "Culture fosters critical thinking and safety-first mindset."],
      ["GOVERN 4.2", "Accountability", "Govern", "Teams document risks and potential impacts."],
      ["GOVERN 4.3", "Organizational practices for testing", "Govern", "Practices enable AI testing and incident identification."],
      ["GOVERN 5.1", "External stakeholder engagement", "Govern", "Mechanisms for stakeholder engagement and feedback."],
      ["GOVERN 5.2", "Feedback incorporation", "Govern", "Processes integrate external feedback."],
      ["GOVERN 6.1", "Third-party risk", "Govern", "Third-party risk policies address AI system risk."],
      ["GOVERN 6.2", "Contingencies for third-party failures", "Govern", "Contingency processes for third-party failures."],
      ["MAP 1.1", "Intended purposes and context", "Map", "Intended purposes and context-specific laws are understood."],
      ["MAP 1.2", "Interdisciplinary collaboration", "Map", "Interdisciplinary AI actors and competencies are defined."],
      ["MAP 1.3", "Mission and goals alignment", "Map", "Mission and relevant goals for the AI are understood."],
      ["MAP 1.4", "Business value or context", "Map", "Business value or context of business use is defined."],
      ["MAP 1.5", "Risk tolerance", "Map", "Organizational risk tolerances are determined."],
      ["MAP 1.6", "System requirements", "Map", "System requirements are elicited from relevant AI actors."],
      ["MAP 2.1", "Task and method definition", "Map", "Tasks and methods of the AI system are defined."],
      ["MAP 2.2", "Knowledge of domain", "Map", "Information about knowledge limits is documented."],
      ["MAP 2.3", "Scientific integrity", "Map", "Scientific integrity and TEVV considerations are identified."],
      ["MAP 3.1", "Benefits characterization", "Map", "Potential benefits of AI functionality are examined."],
      ["MAP 3.2", "Costs characterization", "Map", "Potential costs and risks are examined."],
      ["MAP 3.3", "Application scope", "Map", "Targeted application scope is specified."],
      ["MAP 3.4", "Oversight processes", "Map", "Processes for operator oversight are defined."],
      ["MAP 3.5", "Human oversight", "Map", "Processes for human oversight are defined."],
      ["MAP 4.1", "Risk mapping", "Map", "Approaches for mapping AI technology and legal risks."],
      ["MAP 4.2", "Internal risk controls", "Map", "Internal risk controls for third-party components."],
      ["MAP 5.1", "Likelihood and magnitude of impact", "Map", "Likelihood and magnitude of impacts are characterized."],
      ["MAP 5.2", "Impacts on individuals and communities", "Map", "Personnel enabling feedback on AI impacts."],
      ["MEASURE 1.1", "Risks and impacts selected for measurement", "Measure", "Metrics for measurement of AI risks are selected."],
      ["MEASURE 1.2", "Appropriateness of metrics", "Measure", "Appropriateness of metrics is regularly assessed."],
      ["MEASURE 1.3", "Independent expertise", "Measure", "Internal experts and external stakeholders are consulted."],
      ["MEASURE 2.1", "Test sets and TEVV", "Measure", "Test sets, metrics, and TEVV details are documented."],
      ["MEASURE 2.2", "Human subject evaluations", "Measure", "Evaluations involving human subjects comply with requirements."],
      ["MEASURE 2.3", "System performance", "Measure", "AI system performance is evaluated regularly."],
      ["MEASURE 2.4", "Deployment performance", "Measure", "Deployment-relevant measurement is performed."],
      ["MEASURE 2.5", "Validity and reliability", "Measure", "AI system validity and reliability are evaluated."],
      ["MEASURE 2.6", "Safety", "Measure", "AI system safety risks are evaluated."],
      ["MEASURE 2.7", "Security and resilience", "Measure", "Security and resilience are evaluated."],
      ["MEASURE 2.8", "Explainability and interpretability", "Measure", "Explainability and interpretability are evaluated."],
      ["MEASURE 2.9", "Privacy", "Measure", "Privacy risks are evaluated."],
      ["MEASURE 2.10", "Fairness and bias", "Measure", "Fairness and bias are evaluated."],
      ["MEASURE 2.11", "Environmental impact", "Measure", "Environmental impact and sustainability are evaluated."],
      ["MEASURE 2.12", "Computational requirements", "Measure", "Computational performance and efficiency are evaluated."],
      ["MEASURE 2.13", "Effectiveness of measurement", "Measure", "Effectiveness of measurement is evaluated."],
      ["MEASURE 3.1", "Risk tracking", "Measure", "Approaches for tracking identified risks are established."],
      ["MEASURE 3.2", "Risk response tracking", "Measure", "Tracking approaches for hard-to-measure risks."],
      ["MEASURE 3.3", "Feedback integration", "Measure", "Feedback processes for end users are integrated."],
      ["MEASURE 4.1", "Measurement reliability", "Measure", "Measurement approaches are reviewed for reliability."],
      ["MEASURE 4.2", "Context relevance", "Measure", "Measurement results assess performance in context."],
      ["MEASURE 4.3", "Measurable performance improvements", "Measure", "Measurable performance improvements are evaluated."],
      ["MANAGE 1.1", "Purpose and context", "Manage", "Determination that AI achieves intended purpose."],
      ["MANAGE 1.2", "Risk treatment", "Manage", "Treatment of documented risks is prioritized."],
      ["MANAGE 1.3", "Risk response", "Manage", "Responses to high-priority risks are planned."],
      ["MANAGE 1.4", "Deployment decisions", "Manage", "Residual risks are documented and deployment decided."],
      ["MANAGE 2.1", "Resource allocation", "Manage", "Resources required to manage AI risks are considered."],
      ["MANAGE 2.2", "Mechanisms to sustain value", "Manage", "Mechanisms sustain value of deployed AI systems."],
      ["MANAGE 2.3", "Deactivation procedures", "Manage", "Procedures recover from previously unknown risks."],
      ["MANAGE 2.4", "Override, disengage, deactivate", "Manage", "Mechanisms override, disengage, or deactivate AI systems."],
      ["MANAGE 3.1", "Third-party resources", "Manage", "Risks from third-party resources are monitored."],
      ["MANAGE 3.2", "Pre-trained models", "Manage", "Pre-trained models are monitored for risks."],
      ["MANAGE 4.1", "Post-deployment monitoring", "Manage", "Post-deployment monitoring plans are implemented."],
      ["MANAGE 4.2", "Continual improvement", "Manage", "Continuous improvement activities are integrated."],
      ["MANAGE 4.3", "Incident communication", "Manage", "Incidents and errors are communicated to AI actors."],
    ],
  },
];

window.SEED_POLICIES = [
  { name: "AI Governance Policy", category: "Governance", version: "1.0", owner: "CISO", status: "Approved",
    content: "This policy establishes the organizational commitment to responsible and trustworthy AI across the lifecycle." },
  { name: "Responsible AI Use Policy", category: "Use", version: "1.0", owner: "Data Ethics Lead", status: "Approved",
    content: "Defines acceptable and unacceptable uses of AI systems for employees." },
  { name: "AI Incident Response Plan", category: "Incident", version: "1.0", owner: "Head of AI Risk", status: "Draft",
    content: "Procedure for detecting, triaging, reporting and remediating AI-related incidents." },
];
